name: bloodlink_donor_mobile_app
description: BloodLink Donor Mobile App - A responsive blood donation platform built with Flutter.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/app_logo.png
    - assets/image/children_image.jpg
    - assets/image/profile.jpg
    - assets/image/image.png

flutter_native_splash:
  color: "#F6F7FB"
  image: assets/image/app_logo.png
  android_12:
    image: assets/image/app_logo.png
    icon_background_color: "#F6F7FB"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/app_logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
